const List<String> platforms = [
  "Facebook",
  "Twitter",
  "Instagram",
  "LinkedIn",
  "Pinterest",
  "Reddit",
  "Snapchat",
  "TikTok",
  "Tumblr",
  "Clubhouse",
  "Mastodon",
  "Koo",
  "Chatgpt",
  "Threads",
  "WeChat",
  "LINE",
  "KakaoTalk",
  "Viber",
  "Signal",
  "Telegram",
  "Discord",
  "YouTube",
  "Netflix",
  "Amazon Prime Video",
  "Disney+",
  "Hulu",
  "HBO Max",
  "Vimeo",
  "Dailymotion",
  "Twitch",
  "Hotstar",
  "SonyLIV",
  "Voot",
  "ZEE5",
  "ALTBalaji",
  "MX Player",
  "Pluto TV",
  "Tubi",
  "Roku Channel",
  "Peacock TV",
  "Crackle",
  "Spotify",
  "Apple Music",
  "SoundCloud",
  "Tidal",
  "Pandora",
  "Deezer",
  "Gaana",
  "JioSaavn",
  "Wynk Music",
  "Audiomack",
  "Amazon Music",
  "YouTube Music",
  "iHeartRadio",
  "Stitcher",
  "Pocket Casts",
  "Castbox",
  "Overcast",
  "Google Podcasts",
  "Anchor",
  "TuneIn",
  "Amazon",
  "eBay",
  "Flipkart",
  "Alibaba",
  "Walmart",
  "Etsy",
  "Rakuten",
  "Best Buy",
  "Target",
  "Shopify",
  "Myntra",
  "Ajio",
  "Nykaa",
  "Shein",
  "Meesho",
  "Snapdeal",
  "Lazada",
  "JD.com",
  "Poshmark",
  "BigBasket",
  "Grofers",
  "FreshDirect",
  "Thrive Market",
  "Instacart",
  "GoPuff",
  "Chewy",
  "Home Depot",
  "Wayfair",
  "Lowe’s",
  "Overstock",
  "PayPal",
  "Stripe",
  "Square",
  "Venmo",
  "Zelle",
  "Google Pay",
  "PhonePe",
  "Paytm",
  "Cash App",
  "Apple Pay",
  "HDFC Bank",
  "SBI YONO",
  "ICICI Bank iMobile",
  "Axis Bank",
  "Kotak 811",
  "Chase",
  "Bank of America",
  "Wells Fargo",
  "American Express",
  "Discover",
  "Fidelity",
  "Vanguard",
  "Robinhood",
  "Charles Schwab",
  "Interactive Brokers",
  "Coinbase",
  "Binance",
  "WazirX",
  "Kraken",
  "Crypto.com",
  "Google Drive",
  "Dropbox",
  "OneDrive",
  "iCloud",
  "Box",
  "Mega",
  "WeTransfer",
  "Nextcloud",
  "pCloud",
  "Sync.com",
  "Evernote",
  "Notion",
  "Microsoft Office 365",
  "Google Workspace",
  "Adobe Creative Cloud",
  "Canva",
  "Trello",
  "Asana",
  "Slack",
  "Monday.com",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Stack Overflow",
  "Replit",
  "CodePen",
  "JSFiddle",
  "LeetCode",
  "HackerRank",
  "CodeChef",
  "Kaggle",
  "TopCoder",
  "Codewars",
  "GeeksforGeeks",
  "Coursera",
  "edX",
  "Pluralsight",
  "Codecademy",
  "Udemy",
  "MIT OpenCourseWare",
  "Skype",
  "Zoom",
  "Microsoft Teams",
  "Google Meet",
  "Cisco Webex",
  "GoToMeeting",
  "BlueJeans",
  "Jitsi Meet",
  "Zoho Meeting",
  "Adobe Connect",
  "Uber",
  "Lyft",
  "Ola",
  "Airbnb",
  "Booking.com",
  "Expedia",
  "TripAdvisor",
  "Agoda",
  "MakeMyTrip",
  "Goibibo",
  "Yatra",
  "Cleartrip",
  "Hotels.com",
  "Trivago",
  "KAYAK",
  "Skyscanner",
  "Google Flights",
  "Hopper",
  "Southwest Airlines",
  "Delta Airlines",
  "Khan Academy",
  "Coursera",
  "Udemy",
  "edX",
  "Skillshare",
  "BYJU'S",
  "Unacademy",
  "Duolingo",
  "Rosetta Stone",
  "Memrise",
  "Chegg",
  "Bartleby",
  "Wolfram Alpha",
  "Quizlet",
  "Brainly",
  "Google Classroom",
  "Canvas",
  "Blackboard",
  "Edmodo",
  "Schoology",
  "Steam",
  "Epic Games",
  "Xbox Live",
  "PlayStation Network",
  "Twitch",
  "NVIDIA GeForce Now",
  "Google Stadia",
  "Battle.net",
  "Ubisoft Connect",
  "GOG",
  "Origin",
  "Razer Cortex",
  "Garena Free Fire",
  "PUBG Mobile",
  "Call of Duty Mobile",
  "Fortnite",
  "Genshin Impact",
  "Clash of Clans",
  "Among Us",
  "Minecraft",
  "MyFitnessPal",
  "HealthifyMe",
  "Nike Training Club",
  "Google Fit",
  "Samsung Health",
  "Fitbit",
  "Strava",
  "Headspace",
  "Calm",
  "Sleep Cycle",
  "Flo",
  "Clue",
  "Ovia",
  "Period Tracker",
  "Pregnancy Tracker",
  "BabyCenter",
  "WebMD",
  "Mayo Clinic",
  "Medscape",
  "BetterHelp",
  "Tinder",
  "Bumble",
  "Hinge",
  "OkCupid",
  "Match.com",
  "Plenty of Fish",
  "Coffee Meets Bagel",
  "Happn",
  "Grindr",
  "eHarmony",
  "EliteSingles",
  "Christian Mingle",
  "JSwipe",
  "Shaadi.com",
  "Matrimony.com",
  "Dil Mil",
  "Muslima",
  "SilverSingles",
  "BLK",
  "Woo",
  "Aadhaar Portal",
  "IRCTC",
  "EPFO",
  "Digilocker",
  "Income Tax e-Filing",
  "Passport Seva",
  "GST Portal",
  "UIDAI",
  "RTO Services",
  "UMANG App",
  "MyGov India",
  "eDistrict",
  "State Electricity Boards",
  "Municipal Corporation Portals",
  "Land Record Portals",
  "BHIM UPI",
  "FASTag",
  "National Scholarship Portal",
  "DigiYatra",
  "eCourts",
  "Google Ads",
  "Facebook Ads Manager",
  "HubSpot",
  "Mailchimp",
  "Constant Contact",
  "AWeber",
  "Zoho CRM",
  "Zendesk",
  "Freshdesk",
  "Salesforce",
  "Hootsuite",
  "Buffer",
  "Sprout Social",
  "Semrush",
  "Ahrefs",
  "Moz",
  "Ubersuggest",
  "Google Analytics",
  "Tableau",
  "Power BI",
  "Binance",
  "Coinbase",
  "WazirX",
  "Robinhood",
  "Zerodha",
  "Upstox",
  "Angel Broking",
  "CoinDCX",
  "KuCoin",
  "Huobi",
  "Kraken",
  "Crypto.com",
  "FTX",
  "Bitfinex",
  "Bitstamp",
  "eToro",
  "Deribit",
  "Uniswap",
  "PancakeSwap",
  "Metamask",
  "WhatsApp",
  "Google",
  "Yahoo",
  "Microsoft",
  "Apple",
  "Amazon Alexa",
  "Samsung SmartThings",
  "IFTTT",
  "Nest",
  "Ring",
  "Ancestry",
  "23andMe",
  "Shutterfly",
  "Photobucket",
  "Flickr",
  "Pixabay",
  "Pexels",
  "CanStockPhoto",
  "Dreamstime",
  "Freepik",
  "Behance",
  "Dribbble",
  "DeviantArt",
  "ArtStation",
  "500px",
  "Pixiv",
  "Canva",
  "Figma",
  "Sketch",
  "Adobe XD",
  "Quora",
  "Medium",
  "Substack",
  "WordPress",
  "Blogger",
  "Tumblr",
  "Ghost",
  "Wix",
  "Squarespace",
  "Weebly",
  "Kickstarter",
  "Indiegogo",
  "GoFundMe",
  "Patreon",
  "Ko-fi",
  "Buy Me a Coffee",
  "Tipeee",
  "Fundly",
  "Donorbox",
  "Mightycause",
  "Upwork",
  "Fiverr",
  "Freelancer",
  "PeoplePerHour",
  "Toptal",
  "99designs",
  "Workana",
  "Outsourcely",
  "TaskRabbit",
  "Gigster",
  "Glassdoor",
  "LinkedIn Learning",
  "Monster",
  "Indeed",
  "Naukri",
  "TimesJobs",
  "Shine",
  "CareerBuilder",
  "Dice",
  "AngelList",
  "Stack Exchange",
  "SuperUser",
  "Ask Ubuntu",
  "Math StackExchange",
  "Physics StackExchange",
  "Data Science StackExchange",
  "Cross Validated",
  "Software Engineering StackExchange",
  "Game Dev StackExchange",
  "Biology StackExchange",
  "O’Reilly Learning",
  "PacktPub",
  "Safari Books Online",
  "Lynda",
  "Brilliant",
  "Khan Academy Kids",
  "Code.org",
  "CodeCombat",
  "CS50 Harvard",
  "MIT Scratch",
  "Chess.com",
  "Lichess",
  "Chess24",
  "RedBalloon",
  "Udacity",
  "TeamTreehouse",
  "SoloLearn",
  "FreeCodeCamp",
  "Scrimba",
  "The Odin Project",
  "Socratic",
  "Symbolab",
  "Desmos",
  "Wolfram Mathematica",
  "GeoGebra",
  "Microsoft Math Solver",
  "Kuta Software",
  "Brighterly",
  "PhotoMath",
  "Mathway",
  "FitOn",
  "Peloton",
  "Aaptiv",
  "Nike Run Club",
  "Adidas Running",
  "8fit",
  "StrongLifts",
  "JEFIT",
  "MyPlate",
  "Lifesum",
  "AllTrails",
  "Komoot",
  "MapMyRun",
  "Runkeeper",
  "Sports Tracker",
  "Caliber Fitness",
  "Tone & Sculpt",
  "Daily Burn",
  "Sweat App",
  "Sworkit",
  "Talkspace",
  "BetterUp",
  "7 Cups",
  "Moodfit",
  "MindDoc",
  "Woebot",
  "Youper",
  "Sanvello",
  "Happify",
  "Simple Habit",
  "FloHealth",
  "Ovia Pregnancy",
  "Nurture",
  "Glow",
  "Kindara",
  "Tempdrop",
  "Fertility Friend",
  "Natural Cycles",
  "Ovia Parenting",
  "BabyConnect",
  "Ticketmaster",
  "Live Nation",
  "StubHub",
  "SeatGeek",
  "Eventbrite",
  "Festicket",
  "Dice.fm",
  "Bandsintown",
  "AXS",
  "Songkick",
  "AMC Theatres",
  "Fandango",
  "Atom Tickets",
  "Cinemark",
  "Regal Cinemas",
  "Moviefone",
  "Showtime",
  "Vudu",
  "CinemaNow",
  "Movies Anywhere",
  "Yelp",
  "TripIt",
  "Citymapper",
  "Moovit",
  "Rome2Rio",
  "Bolt",
  "Cabify",
  "BlaBlaCar",
  "Lyft Business",
  "Curb",
  "Duet Display",
  "Astropad",
  "Yousician",
  "Simply Piano",
  "GuitarTuna",
  "Melodics",
  "MuseScore",
  "Pianote",
  "Chordify",
  "Perfect Ear",
  "Codecademy",
  "DataCamp",
  "Databricks Academy",
  "Google Cloud Training",
  "AWS Training",
  "Microsoft Learn",
  "Linux Academy",
  "SAP Learning Hub",
  "Udacity AI School",
  "Fast.ai",
  "Cloudflare",
  "Akamai",
  "Sucuri",
  "Imperva",
  "SiteGround",
  "Bluehost",
  "HostGator",
  "Namecheap",
  "DreamHost",
  "GoDaddy",
  "Shopify Plus",
  "BigCommerce",
  "Magento",
  "WooCommerce",
  "Volusion",
  "Squarespace Commerce",
  "PrestaShop",
  "OpenCart",
  "Ecwid",
  "Weebly Commerce",
  "Poshmark",
  "Depop",
  "ThredUp",
  "Tradesy",
  "Rebag",
  "The RealReal",
  "Vestiaire Collective",
  "Vinted",
  "Grailed",
  "StockX",
  "Crunchyroll",
  "Funimation",
  "VRV",
  "HIDIVE",
  "AnimeLab",
  "MyAnimeList",
  "Kitsu",
  "AniList",
  "9anime",
  "GoGoAnime",
  "Amino",
  "BandLab",
  "Smule",
  "SingSnap",
  "Voloco",
  "Voisey",
  "RapChat",
  "BeatStars",
  "Trackd",
  "Soundtrap",
  "Investopedia",
  "Morningstar",
  "Seeking Alpha",
  "The Motley Fool",
  "Yahoo Finance",
  "Benzinga",
  "CoinGecko",
  "Token Metrics",
  "DappRadar",
  "Messari",
  "Glassdoor Reviews",
  "Blind",
  "The Ladders",
  "Fairygodboss",
  "Fishbowl",
  "Handshake",
  "WayUp",
  "MightyRecruiter",
  "Workana",
  "Outsourcely",
  "HackerOne",
  "Bugcrowd",
  "Synack",
  "Intigriti",
  "Cobalt",
  "Open Bug Bounty",
  "SafeHats",
  "YesWeHack",
  "ZeroDay Initiative",
  "Snyk",
  "NordVPN",
  "ExpressVPN",
  "CyberGhost",
  "Surfshark",
  "Private Internet Access",
  "TunnelBear",
  "VyprVPN",
  "ProtonVPN",
  "Windscribe",
  "Mullvad",
  "Parallels",
  "VMware",
  "VirtualBox",
  "Boot Camp",
  "WineHQ",
  "Docker",
  "Kubernetes",
  "Red Hat OpenShift",
  "Rancher",
  "Podman",
  "SoundCloud Pro",
  "Mixcloud",
  "Beatport",
  "Juno Download",
  "Bandcamp",
  "Splice",
  "Loopmasters",
  "Tracklib",
  "Audius",
  "Soundstripe",
  "QuickBooks",
  "Xero",
  "Zoho Books",
  "Wave Accounting",
  "FreshBooks",
  "Sage Accounting",
  "Tally ERP",
  "FreeAgent",
  "NetSuite",
  "MYOB",
  "Revolut",
  "N26",
  "Monzo",
  "Starling Bank",
  "Chime",
  "Varo",
  "Aspiration",
  "Simple",
  "Current",
  "Wealthfront",
  "Todoist",
  "Things",
  "Microsoft To Do",
  "Google Keep",
  "Evernote Business",
  "OneNote",
  "Notability",
  "GoodNotes",
  "Bear",
  "Simplenote",
  "Anki",
  "RemNote",
  "SuperMemo",
  "Quizlet Plus",
  "Brainscape",
  "Memrise Pro",
  "Flashcards Deluxe",
  "Cram",
  "StudyBlue",
  "Smartr",
  "Zotero",
  "Mendeley",
  "EndNote",
  "RefWorks",
  "Paperpile",
  "Citavi",
  "Colwiz",
  "JabRef",
  "ReadCube",
  "Scrivener",
  "Figma Mirror",
  "Adobe Fresco",
  "Procreate",
  "Affinity Designer",
  "Affinity Photo",
  "Clip Studio Paint",
  "CorelDRAW",
  "Sketchbook",
  "PaintTool SAI",
  "Krita",
  "OmniFocus",
  "Things 3",
  "Sorted 3",
  "Agenda",
  "TickTick",
  "Habitica",
  "Loop Habit Tracker",
  "Way of Life",
  "Streaks",
  "Goal Tracker",
  "Freedom",
  "Cold Turkey",
  "StayFocusd",
  "Forest App",
  "RescueTime",
  "Serene",
  "LeechBlock",
  "Mindful Browsing",
  "SelfControl",
  "Focus Keeper"
];
