// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOKalgXCrtDd9aGCZTCgdpYWf1ADdPja4',
    appId: '1:187086706775:web:588e2dea95ced8bdac2b12',
    messagingSenderId: '187086706775',
    projectId: 'password-manager-89a69',
    authDomain: 'password-manager-89a69.firebaseapp.com',
    storageBucket: 'password-manager-89a69.firebasestorage.app',
    measurementId: 'G-9BMW4R99MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhRoPsDHl26t9ErXb2os9EBXA_q1-9ORU',
    appId: '1:187086706775:android:c41289493b81b472ac2b12',
    messagingSenderId: '187086706775',
    projectId: 'password-manager-89a69',
    storageBucket: 'password-manager-89a69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzX02srhDLn4NQuSPT-sPLhdk8X8Pnh4Y',
    appId: '1:187086706775:ios:3b2c796de32ce7bdac2b12',
    messagingSenderId: '187086706775',
    projectId: 'password-manager-89a69',
    storageBucket: 'password-manager-89a69.firebasestorage.app',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzX02srhDLn4NQuSPT-sPLhdk8X8Pnh4Y',
    appId: '1:187086706775:ios:3b2c796de32ce7bdac2b12',
    messagingSenderId: '187086706775',
    projectId: 'password-manager-89a69',
    storageBucket: 'password-manager-89a69.firebasestorage.app',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOKalgXCrtDd9aGCZTCgdpYWf1ADdPja4',
    appId: '1:187086706775:web:019f419ad498dac1ac2b12',
    messagingSenderId: '187086706775',
    projectId: 'password-manager-89a69',
    authDomain: 'password-manager-89a69.firebaseapp.com',
    storageBucket: 'password-manager-89a69.firebasestorage.app',
    measurementId: 'G-0HF3X1M3YK',
  );
}
